version: "3.8"
services:
  nestapp:
    image: styleflow/styleflow-latest
    ports:
      - "4001:4000"
    env_file: 
      - .env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgdata: